name: Install Savi
description: A GitHub Action to install Savi in the current job runner.
inputs:
  version:
    description: The version of Savi to install.
    required: false
    default: latest
runs:
  using: "composite"
  steps:
    - name: Install asdf
      uses: asdf-vm/actions/setup@v1

    - name: Install asdf plugin for Savi
      shell: bash
      run: asdf plugin add savi https://github.com/savi-lang/asdf-savi.git

    - name: Install specified Savi version
      uses: asdf-vm/actions/install@v1
      with:
        tool_versions: savi ${{inputs.version}}

    - name: Select specified Savi version locally
      shell: bash
      run: asdf local savi ${{inputs.version}}
